### ISSUE TITLE
Transition hole

### ISSUE THREAD

**Issue by opula** [ibitcy/react-native-hole-view#1]
Hello,

Great library and easy to use.  I was wonder if it's possible to transition the hole from one set of params to another?  This would happen in a similar fashion to [react-native-copilot](https://github.com/mohebifar/react-native-copilot).

**Comment by stephenkopylov** [comment]
Hey @opula check out our new feature in v2.0.0 - animated transitions!

**Comment by opula** [comment]
Awesome work @stephenkopylov. I'll go ahead and close this!
