### ISSUE TITLE
Execution failed for task ':react-native-hole-view:compileDebugKotlin'.

### ISSUE THREAD

**Issue by camboYY** [ibitcy/react-native-hole-view#14]
i have upgraded :
 minSdkVersion = 21
  compileSdkVersion = 33
  targetSdkVersion = 33

FAILURE: Build failed with an exception

System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 427.18 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
e: /Users/yous.yoeun/Documents/robotech-repo/cdrb-flow-app/node_modules/react-native-hole-view/android/src/main/java/com/ibitcy/react_native_hole_view/RNHoleView.kt: (172, 17): 'onAnimationRepeat' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-hole-view:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by andybui090** [comment]
Me too

**Comment by stephenkopylov** [comment]
@camboYY @andybui090 Hey!

New version (2.1.2) is just released - please try it out. The problem must be fixed

**Comment by camboYY** [comment]
hi @stephenkopylov thank work fine
