### ISSUE TITLE
[android]: unable to click on a TouchableOpacity in React Native 0.70.5

### ISSUE THREAD

**Issue by yepMad** [ibitcy/react-native-hole-view#15]
Hello,

I see all the drama about clicks through the hole on Android. Maybe I misunderstood, but it should work, right? There's a dirty solution behind it all but it should work, is it?

In react-native 0.70.5 the Scroll works, but the click on TouchableOpacity does not. Is this expected?

**Comment by yepMad** [comment]
Hey @stephenkopylov. I might try to do that soon, but I'll try to explain it quickly to get it documented.

My code is below. I'm using the RNHoleView inside a Context/Provider at the top of my app, "{children}" is the whole app stack (Navigators, Screens, etc). Clicking doesn't work anywhere in the app. But the scroll does.

![image](https://user-images.githubusercontent.com/22564368/208151804-9ce39e6f-8d61-4604-9006-6e98d26ce96e.png)

Sorry I can't provide an example right now, I hope I can do that soon. Thanks for the quick response!

**Comment by stephenkopylov** [comment]
Hep @yepMad I'd suggest you to try following:

put {children} block inside RNHoleView

Something like this:

```
<RNHoleView>
{children}
</RNHoleView>
```

This way it should work (but who knows - we never faced 0.70+ versions yet)

**Comment by sintylapse** [comment]
Hey @yepMad , did you find out how to fix the issue? This problem still persists

**Comment by juskk** [comment]
still now working, right?

**Comment by zabojad** [comment]
Try PR https://github.com/ibitcy/react-native-hole-view/pull/22 it should fix your touch issue...

**Comment by stephenkopylov** [comment]
Please try version 3.0.0-alpha3. It still needs some testing but should work.

**Comment by juskk** [comment]
it does thank you

**Comment by juskk** [comment]
hi @stephenkopylov, touches does work when I put RNHoleView directly inside a component, but when I try to place it above navigation so I can handle it in the whole app only scrolling works on android, iOS is still fine. could you please take a look at it

**Comment by stephenkopylov** [comment]
Hi @juskk! 

Could you please prepare and upload to the github some kind of sample project illustrating this problem using for example create-react-native-app?

**Comment by juskk** [comment]
Hi @stephenkopylov

It's pretty simple so I'm not sure if I need to push it to git. 
Structure: App->Handler(here touches doesnt work)->Navigation->Page(here they do)
React Native v. 0.71.0, empty project created with create-react-native-app.

<img width="564" alt="image" src="https://github.com/ibitcy/react-native-hole-view/assets/71719203/0a9a53d3-44f0-4b58-b46d-6fabe42b90ed">
<img width="845" alt="image" src="https://github.com/ibitcy/react-native-hole-view/assets/71719203/245eee09-c86c-4c4e-a8e8-93dddcd02801">
<img width="565" alt="image" src="https://github.com/ibitcy/react-native-hole-view/assets/71719203/baaf721d-f6c2-4a14-9450-d8bdd9d0fd39">
<img width="845" alt="image" src="https://github.com/ibitcy/react-native-hole-view/assets/71719203/e8aaacc6-5451-4064-8289-0495d3fff090">


Please tell me if I still need to push it to git.

**Comment by stephenkopylov** [comment]
Hi @juskk - the way you use react-native-hole view is a little bit incorrect

Please put your <Navigation/> **inside** <RNHoleView>

Like this:
```
<RNHoleView>
   <Navigation/>
</RNHoleView>
```

Otherwise you'll not be able to click to your navigation stack

**Comment by juskk** [comment]
This way I have issues with RNHoleView background, its absent, while the transparent area is no more transparent. 
So is it the only solutions, it won't work the way I tried on android even tho it does on iOS? 

Thanks in advance for your help

**Comment by stephenkopylov** [comment]
Sorry for misleading you're right - it should work without putting your content inside `<RNHoleView>`

Give me some time - I'll try to fix it 

It' would be great if you prepare repro-project just to save my time :)

**Comment by sintylapse** [comment]
Doesn't seem to be working for Android even with 3.0.0-alpha3

**Comment by sintylapse** [comment]
Simple workaround is to capture press event and detecting if it's in the area of the hole, like that

```
<View onResponderRelease={({ nativeEvent: { pageX, pageY } }) => {
    const isWithinX = pageX > holeX && pageX < holeX + holeWidth;
    const isWithinY = pageY > holeY && pageY < holeY + holeHeight;

  const isPressedOnHole = isWithinX && isWithinY;

  if (isPressedOnHole) {
    onPressedInsideHole();
  }
}} >
```
