### ISSUE TITLE
Flickering after some animations passed

### ISSUE THREAD

**Issue by serjek** [ibitcy/react-native-hole-view#19]
Hello, thank you for this nice lib! Being playing with example project I noticed a slight but nasty flickering of holes after several rounds of animation , see attached video.

https://user-images.githubusercontent.com/18265157/218541239-316212f0-5ce5-42ef-aac2-ec70c199faab.mov

**Comment by stephenkopylov** [comment]
@serjek Hi and thank you for finding this strange bug

Could you please share any details? 
Like iOS simulator version? xcode version? Is it reproducible on physical device?

I tried to reproduce it in simulator (iPhone 14, iOS 16.2) but had no success:

https://user-images.githubusercontent.com/5202281/218544578-eb223bbb-4c82-47b7-b520-9b2759194f3a.mov

**Comment by serjek** [comment]
Hey sure, XCode Version 14.2 (14C18), reproduced on simulator (iPhone 12, 15.2), but didn't repro on real device - iPhone 12 mini, 16.1.1. Perhaps it's sim specific. if you don't mind I would close it for now.
