### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by leo-bo** [ibitcy/react-native-hole-view#2]
Dear team behind `react-native-hole-view`,

First of all, thanks a lot for your work! We use your library since version `1.0.0` and are happy with it!
One minor suggestion would be to include a file with changelog into the repo, so that it would be easier to see what changed from version to version and come up with how our code needs to be adapted to keep up (say, `IRNHole` seems to be gone and now I should probably use `RNHole` instead).

Other than that, great job and thanks once again! 👍

**Comment by stephenkopylov** [comment]
Hello @leo-bo thank you for king words! :)

We added changelog and from now will try to fill it more carefully

https://github.com/ibitcy/react-native-hole-view/blob/master/CHANGELOG.md
