### ISSUE TITLE
Gradle plugin deprecated

### ISSUE THREAD

**Issue by vikrantnegi** [ibitcy/react-native-hole-view#20]
Hi, I'm getting warning when trying to upgrade my gradle in Android.

The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

**Comment by stephenkopylov** [comment]
Hi @vikrantnegi 

Sorry, but we're not going to make a migration only because of warnings - RN itself and lots of it's libraries are full of warnings

But if you'd like to migrate the library to View Binding - feel free to make a PR

**Comment by ManeeshBusi** [comment]
Hey @stephenkopylov,
I just installed the package on a new project and i've been getting the same error. It's preventing me from building the app and running it. Is there a workaround for this issue or is it something from my end?

**Comment by stephenkopylov** [comment]
Hi again guys! The issue should be fixed in v2.2.1
Please take a look :) 

PS: @vikrantnegi thanks for your advice!
