### ISSUE TITLE
Support for new architecture

### ISSUE THREAD

**Issue by zabojad** [ibitcy/react-native-hole-view#21]
Hi there! Am I wrong or does this module **not** support the new architecture (Fabric) ?

**Comment by zabojad** [comment]
https://github.com/ibitcy/react-native-hole-view/pull/22

**Comment by ronlobo01** [comment]
@zabojad are you facing this issue `> Task :react-native-hole-view:compileReleaseKotlin FAILED` while generating build.

Is your issue related to this ?

**Comment by zabojad** [comment]
@ronlobo01 No, I'm not. And no, it's probably not related... My work compiles on Android both with and without new arch...

**Comment by zabojad** [comment]
FYI the PR is now fully functional on Android (both new and old architecture)
