### ISSUE TITLE
dynamic hole

### ISSUE THREAD

**Issue by fukemy** [ibitcy/react-native-hole-view#24]
Hi, I want to create facebook message gradient effect like this:
![7d07db2e-8c43-4af8-86e4-d6369b7decc5](https://github.com/ibitcy/react-native-hole-view/assets/8202437/fd312803-c360-4b91-b20d-32f898708b7c)

THen I found hold-view can do it (I think so)
As the Image above, the massageContainer is white background then the holdview is the `TextMessage`, that hard to calculate position. So I want to ask do you provide hold item as a child like this? Thanks so much

**Comment by fukemy** [comment]
I tried to using like this::
```
<RNHoleView>
<RNHole>
   <TextMessage/>
</RNHole>
</RNHoleView>
```

But it not working

**Comment by stephenkopylov** [comment]
If I understand it right - you need to highlight some message in your chat's scrollview

The only way to do it is to calculate the absolute bounding box of your message's view and apply this bounding box as a hole to RNHoleView

This library doesn't provide this kind of functionality so you should write it by yourself

**Comment by fukemy** [comment]
hell thanks you
