### ISSUE TITLE
hole view with blur effect

### ISSUE THREAD

**Issue by rbayuokt** [ibitcy/react-native-hole-view#3]
Hi, I love your work , I have a request is it possible to make the view is blur ? and the hole is transparent, I think it will be good if there is any option for this, thank you so much

**Comment by stephenkopylov** [comment]
Hi @rbayuokt!
Just try to put https://github.com/Kureev/react-native-blur into our **react-native-hole-view** 
Probably it gonna work

**Comment by stephenkopylov** [comment]
Hey @rbayuokt ! 
Did you try the workaround using react-native-blur?

**Comment by stephenkopylov** [comment]
@rbayuokt 
I'm closing the issue due to inactivity. Feel free to reopen it if you wont find any solution for this case
