### ISSUE TITLE
Compilation failure, Android with RN 0.73.1

### ISSUE THREAD

**Issue by dcorbin** [ibitcy/react-native-hole-view#30]
/react_native_hole_view/RNHoleView.kt:179:5 'onDraw' overrides nothing

I'm upgrading my project's version of React Native from 0.72.8 to 0.73.1.   Now the Android build fails with the above error, near as I can tell.   I presume this is a result of the introduction of Bridgeless Mode that happen in 0.73.  Is it possible to enable new architecture and Fabric in this project?

**Comment by dcorbin** [comment]
1) Create a new React project: `npx react-native init project`
2) add react-native-hole-view to the project: `yarn add react-native-hole-view`
3) Run the project on Android: `npx react-native run-android`

Sample Repo: https://github.com/dcorbin/rnhv_compile_bug_RN0.73.1

**Comment by dcorbin** [comment]
I've determined that this is a problem because of android SDK 34.  When I roll back to 33, it works fine.  (But new RN projects are made with 34).

**Comment by nonam4** [comment]
+1

**Comment by stephenkopylov** [comment]
@dcorbin please check out v3.0.0-alpha4

**Comment by dcorbin** [comment]
I can confirm that the problem is fixed in 3.0.0-alpha4

Thanks much.
