### ISSUE TITLE
animation doesn't work

### ISSUE THREAD

**Issue by ikibis25** [ibitcy/react-native-hole-view#6]
<img width="268" alt="Снимок экрана 2021-06-09 в 19 06 01" src="https://user-images.githubusercontent.com/74191485/121390757-5b3c9700-c956-11eb-9ead-6723cdb0c1c2.png">

Hello :)
I try your third example and I get this error

 LOG  BugReporting extraData: {"AppRegistry.runApplication1": "Running \"testApp\" with {\"rootTag\":31,\"initialProps\":{\"isHeadless\":false}}"}
 WARN  Possible Unhandled Promise Rejection (id: 1):
Error: You attempted to set the key `duration` with the value `200` on an object that is meant to be immutable and has been frozen.

react-native 0.61.0

**Comment by avet-m** [comment]
@ikibis25 Hello! 

please follow [this example](https://github.com/ibitcy/react-native-hole-view/blob/master/example/App.tsx)

If error you mentioned above will happen again, let us know about it and provide some code snip, please

**Comment by antila3567** [comment]
try delete
 useEffect(() {
    onPress();
 }, []);

**Comment by stephenkopylov** [comment]
@ikibis25 hey!

We checked the example and it seems to work fine 
![Screenshot 2021-06-10 at 16 36 20](https://user-images.githubusercontent.com/5202281/121543795-e169e380-ca11-11eb-964e-89a8c62915c5.png)

Anyway - we've made few fixes + updated Readme - so now it's much easier to run the example

**Comment by stephenkopylov** [comment]
@ikibis25 
closing the issue - feel free to reopen it if you'll face any difficulties working with the lib =)
